name: 'Playground'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token:
    required: true
    description: 'token'
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
